# Generated by Django 3.0.1 on 2020-07-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contact_mail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mail_status_discription',
            field=models.CharField(default='asdadas', max_length=1000),
            preserve_default=False,
        ),
    ]
